pipelines:
      default:
        - step:
            name: Sync GitHub Mirror
            image: alpine/git:latest
            clone:
              enabled: false
            script:
              - git clone --bare git@bitbucket.org:hiroshiaki/rnmlkit.git
              - cd rnmlkit.git
              - git push --mirror git@github.com:rahmanazhar/RNMLKit.git